apiVersion: apps/v1
kind: Deployment
metadata:
  name: jparest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jparest
  template:
    metadata:
      labels:
        app: jparest
      name: jparest
    spec:
      containers:
      - image: manishkumar2020/jparest:v1
        imagePullPolicy: Always
        name: jparest
