apiVersion: apps/v1
kind: Deployment
metadata:
  name: jparest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jparest
  template:
    metadata:
      labels:
        app: jparest
      name: jparest
    spec:
      containers:
      - image: manishkumar2020/jparest:2a3319d
        imagePullPolicy: Always
        name: jparest
