apiVersion: v1
kind: Service
metadata:
  labels:
    app: jparest
  name: jparest
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jparest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jparest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jparest
  template:
    metadata:
      labels:
        app: jparest
      name: jparest
    spec:
      containers:
      - image: manishkumar2020/jparest:7bfc06d
        imagePullPolicy: Always
        name: jparest
